// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'fields_test.dart' as fields_test;
import 'groups_test.dart' as groups_test;
import 'hierarchy_test.dart' as hierarchy_test;
import 'monoids_test.dart' as monoids_test;

void main() {
  monoids_test.main();
  hierarchy_test.main();
  groups_test.main();
  fields_test.main();
}
