name: abstract_dart
description: Abstract Dart!
author: Modestas Valauskas <valauskasmodestas+dartpub@gmail.com>
homepage: https://github.com/modulovalue/abstract_dart
repository: https://github.com/modulovalue/abstract_dart
issue_tracker: https://github.com/modulovalue/abstract_dart/issues
version: 0.0.1

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  decimal: ^0.3.4

dev_dependencies:
  test: ^1.6.6
  extra_pedantic: ^1.0.0