name: abstract_dart
description: A collection of algebraic structures borrowed from abstract algebra. Semigroup, Monoid, Group & Field.
author: Modestas Valauskas <valauskasmodestas+dartpub@gmail.com>
homepage: https://github.com/modulovalue/abstract_dart
repository: https://github.com/modulovalue/abstract_dart
issue_tracker: https://github.com/modulovalue/abstract_dart/issues
version: 2.0.0

environment:
  sdk: '>=2.4.4 <3.0.0'

dependencies:
  decimal: ^0.3.5

dev_dependencies:
  test: ^1.6.6
  extra_pedantic: ^1.2.0
  test_coverage: ^0.2.0
